### ISSUE TITLE
串口调试和DAP下载无法同时使用

### ISSUE THREAD

**Issue by ShoiLyaung** [wuxx/nanoDAP-HS-wireless#1]
连接后如果进行DAP下载，则无法使用串口调试；如果先用串口调试则无法DAP下载

**Comment by wuxx** [comment]
你好，请问使用的是普通速度版本还是高速版本

**Comment by ShoiLyaung** [comment]
高速无线版

**Comment by ghoker143** [comment]
问题相同

**Comment by wuxx** [comment]
好的，这边看看，后面可以更新固件解决

**Comment by ghoker143** [comment]
测试了一下，似乎和距离有关，主机从机距离越远串口和debug越容易互相干扰

**Comment by ShoiLyaung** [comment]
请问要怎么更新固件，有新的固件版本吗

**Comment by ShoiLyaung** [comment]
请问要怎么更新固件，有新的固件版本吗

**Comment by yry0008** [comment]
高速下载器的这个版本到现在好像还是用不了串口啊

**Comment by wuxx** [comment]
可以使用，只不过由于串口和下载共用同一个带宽，会形成互相抢占，造成一定影响，所以一般推荐如果使用串口的话，数据量不要太大。

**Comment by wuxx** [comment]
后续会推出带外置天线的，增强无线性能
