### ISSUE TITLE
nanoDAP-HS如果串口U_RX脚拉5V会一直链不上USB

### ISSUE THREAD

**Issue by driftregion** [wuxx/nanoDAP-HS-wireless#3]
找了一会儿发现我单片机串口TX线5V拉高是不能无效的。同时发现nanoDAP-HS如果在启动那一瞬间U_RX脚拉到5V、它就会链不上电脑。
请在文档里面提出串口不支持5V、或者提出我们用户应该不要拉U_RX高在nanoDAP-HS启动时。谢谢！

**Comment by wuxx** [comment]
你好，MCU的IO电平默认都是3.3V的，包括串口的IO电平，若接到5V，则可能会产生不可预知的后果
